### ISSUE TITLE
eternal_checker.py  error

### ISSUE THREAD

**Issue by gearcapitan** [3ndG4me/AutoBlue-MS17-010#16]
    /home/w/Do/H/N/AutoBlue-MS17-010  on   master !8 ?1    ✔ ▓▒░ python eternal_checker.py 10.10.10.178
Traceback (most recent call last):
  File "eternal_checker.py", line 89, in <module>
    main()
  File "eternal_checker.py", line 66, in main
    conn = MYSMB(options.target_ip, int(options.port))
  File "/home/warmachine/Documentos/HTB/Nest/AutoBlue-MS17-010/mysmb.py", line 122, in __init__
    smb.SMB.__init__(self, remote_host, remote_host, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 2427, in __init__
    self.neg_session()
  File "/home/warmachine/Documentos/HTB/Nest/AutoBlue-MS17-010/mysmb.py", line 178, in neg_session
    smb.SMB.neg_session(self, extended_security=self.__use_ntlmv2, negPacket=negPacket)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 2642, in neg_session
    smb = self.recvSMB()
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb.py", line 2506, in recvSMB
    r = self._sess.recv_packet(self.__timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 914, in recv_packet
    data = self.__read(timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 996, in __read
    data = self.read_function(4, timeout)
  File "/usr/local/lib/python2.7/dist-packages/impacket/nmb.py", line 983, in non_polling_read
    received = self._sock.recv(bytes_left)
socket.error: [Errno 104] Connection reset by peer

**Comment by pwnhun73r** [comment]
In the new version of kali 2020.2 my solution was:
sudo apt-get install python-pip
sudo pip install impacket

**Comment by 3ndG4me** [comment]
There was also an issue in the `mysmb.py` script that has now been resolved by PR #17 

Closing this out.
