### ISSUE TITLE
ImportError: No module named impacket

### ISSUE THREAD

**Issue by phanthuthao** [3ndG4me/AutoBlue-MS17-010#28]
python eternal_checker.py 192.168.0.102 
Traceback (most recent call last):
  File "eternal_checker.py", line 1, in <module>
    from mysmb import MYSMB
  File "/home/kali/soft/AutoBlue-MS17-010/mysmb.py", line 3, in <module>
    from impacket import smb, smbconnection
ImportError: No module named impacket

pls help me. I had run: pip install impacket , but not working

**Comment by hvegav** [comment]
Try python3 eternal_checker.py 192.168.0.102

**Comment by MacLeo98** [comment]
> Try python3 eternal_checker.py ip
 I have tried but it shows :->

                                                                                                                                                                        
┌──(root💀HACKER)-[/opt/AutoBlue-MS17-010]
└─# python3 eternal_checker.py 192.168.213.150
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/impacket/nmb.py", line 901, in _setup_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/AutoBlue-MS17-010/eternal_checker.py", line 89, in <module>
    main()
  File "/opt/AutoBlue-MS17-010/eternal_checker.py", line 66, in main
    conn = MYSMB(options.target_ip, int(options.port))
  File "/opt/AutoBlue-MS17-010/mysmb.py", line 122, in __init__
    smb.SMB.__init__(self, remote_host, remote_host, timeout=timeout)
  File "/usr/lib/python3/dist-packages/impacket/smb.py", line 2434, in __init__
    self._sess = nmb.NetBIOSTCPSession(my_name, remote_name, remote_host, host_type, sess_port, self.__timeout)
  File "/usr/lib/python3/dist-packages/impacket/nmb.py", line 892, in __init__
    NetBIOSSession.__init__(self, myname, remote_name, remote_host, remote_type=remote_type, sess_port=sess_port,
  File "/usr/lib/python3/dist-packages/impacket/nmb.py", line 752, in __init__
    self._sock = self._setup_connection((remote_host, sess_port), timeout)
  File "/usr/lib/python3/dist-packages/impacket/nmb.py", line 904, in _setup_connection
    raise socket.error("Connection error (%s:%s)" % (peer[0], peer[1]), e)
OSError: [Errno Connection error (192.168.213.150:445)] [Errno 113] No route to host


Anyone could plz help, will be much appreciate ,TQ

**Comment by 3ndG4me** [comment]
Outside of the initial dependency error this is simply a connectivity discrepancy and is definitely isolated to your user case unfortunately. Without further details on your system or your target I cannot assist. There's not an actual issue with the code over all though so unfortunately this is not a proper issue for this. As a person I am happy to help troubleshoot but as a repo maintainer this is totally invalid as I have a whole team using this almost daily without issues and the code has remained unchanged for quite some time.

Best of luck! Feel free to provide more detail but unfortunately I cannot insure support, I'd recommend taking this issue to a community of offsec enthusiasts rather than this repo since it is not a bug.
