### ISSUE TITLE
Fix?

### ISSUE THREAD

**Issue by TheProphecy** [3ndG4me/AutoBlue-MS17-010#3]
`python eternalblue_checker.py xxx.xxx.xxx.xxx
Target OS:
Traceback (most recent call last):
  File "eternalblue_checker.py", line 42, in <module>
    conn.login(USERNAME, PASSWORD)
  File "/root/AutoBlue-MS17-010/mysmb.py", line 152, in login
    smb.SMB.login(self, user, password, domain, lmhash, nthash, ntlm_fallback)
TypeError: login() takes at most 6 arguments (7 given)
`

**Comment by TheProphecy** [comment]
Just read up on it, found a fix here https://github.com/worawit/MS17-010/issues/13
