### ISSUE TITLE
eternalblue_cheker.py error

### ISSUE THREAD

**Issue by amagrupp** [3ndG4me/AutoBlue-MS17-010#4]
eython eternalblue_checker.py 96.126.*.*
[*] exec: python eternalblue_checker.py 96.126.*.*

Traceback (most recent call last):
  File "eternalblue_checker.py", line 42, in <module>
    conn.login(USERNAME, PASSWORD)
  File "/root/autoblue/mysmb.py", line 152, in login
    smb.SMB.login(self, user, password, domain, lmhash, nthash, ntlm_fallback)
  File "/usr/lib/python2.7/dist-packages/impacket/smb.py", line 3340, in login
    self.login_extended(user, password, domain, lmhash, nthash, use_ntlmv2 = True)
  File "/root/autoblue/mysmb.py", line 160, in login_extended
Target OS:
    smb.SMB.login_extended(self, user, password, domain, lmhash, nthash, use_ntlmv2)
  File "/usr/lib/python2.7/dist-packages/impacket/smb.py", line 3250, in login_extended
    type3, exportedSessionKey = ntlm.getNTLMSSPType3(auth, respToken['ResponseToken'], user, password, domain, lmhash, nthash, use_ntlmv2 = use_ntlmv2)
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 618, in getNTLMSSPType3
    ntResponse, lmResponse, sessionBaseKey = computeResponse(ntlmChallenge['flags'], ntlmChallenge['challenge'], clientChallenge, serverName, domain, user, password, lmhash, nthash, use_ntlmv2 )
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 36, in computeResponse
    lmhash, nthash, use_ntlmv2=use_ntlmv2)
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 899, in computeResponseNTLMv2
    av_pairs = AV_PAIRS(serverName)
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 206, in __init__
    self.fromString(data)
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 229, in fromString
    fType = struct.unpack('<H',tInfo[:struct.calcsize('<H')]

Help!!!!!!

**Comment by amagrupp** [comment]
Traceback (most recent call last):
  File "eternalblue_checker.py", line 42, in <module>
    conn.login(USERNAME, PASSWORD)
  File "/root/autoblue/mysmb.py", line 152, in login
    smb.SMB.login(self, user, password, domain, lmhash, nthash, ntlm_fallback)
  File "/usr/lib/python2.7/dist-packages/impacket/smb.py", line 3340, in login
    self.login_extended(user, password, domain, lmhash, nthash, use_ntlmv2 = True)
  File "/root/autoblue/mysmb.py", line 160, in login_extended
    smb.SMB.login_extended(self, user, password, domain, lmhash, nthash, use_ntlmv2)
  File "/usr/lib/python2.7/dist-packages/impacket/smb.py", line 3250, in login_extended
Target OS:
    type3, exportedSessionKey = ntlm.getNTLMSSPType3(auth, respToken['ResponseToken'], user, password, domain, lmhash, nthash, use_ntlmv2 = use_ntlmv2)
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 618, in getNTLMSSPType3
    ntResponse, lmResponse, sessionBaseKey = computeResponse(ntlmChallenge['flags'], ntlmChallenge['challenge'], clientChallenge, serverName, domain, user, password, lmhash, nthash, use_ntlmv2 )
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 36, in computeResponse
    lmhash, nthash, use_ntlmv2=use_ntlmv2)
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 899, in computeResponseNTLMv2
    av_pairs = AV_PAIRS(serverName)
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 206, in __init__
    self.fromString(data)
  File "/usr/lib/python2.7/dist-packages/impacket/ntlm.py", line 229, in fromString
    fType = struct.unpack('<H',tInfo[:struct.calcsize('<H')])[0]
struct.error: unpack requires a string argument of length 2

**Comment by amagrupp** [comment]
https://github.com/worawit/MS17-010/issues/13

a similar problem


line 42 in this case is solved. but 157 there. need a solution!

**Comment by 3ndG4me** [comment]
Thanks for pointing this out, I'll be sure to look into it and apply the appropriate fixes you referenced as soon as possible

**Comment by 3ndG4me** [comment]
Added in the fixes you referenced from 
https://github.com/worawit/MS17-010/issues/13

Thanks for pointing this out! Apologies for the wait!
